### ISSUE TITLE
Fix for hitting request limit?

### ISSUE THREAD

**Issue by Nateliason** [jordan-wright/rapportive#5]
Hey Jordan,

I've been using this rapportive "API" (I love it by the way) and when I do it too often I get an error about making too many requests. I made a small change to your rapportive.py code to return this instead of breaking the function, it's on line 85 and looks like this:

' ' '
if 'error' in response: #checking if we're calling too often
        return 'error'
elif response['status'] == 200 and session_token:
' ' '

**Comment by jordan-wright** [comment]
Thanks, I'll be looking into this. I'll probably upload a fix soon.

**Comment by Nateliason** [comment]
Awesome, thank you! I'll see if I can find a way around the request limit as well in the mean time.

**Comment by jordan-wright** [comment]
Fixed #5 in commit 3b5cf37fba.

Thanks for looking into this!

**Comment by mmahalwy** [comment]
any work around for the limits?

**Comment by mrbirl** [comment]
Randomise the auth email address, and change the IP address your sending from - that combo does the job for me.
