### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'name'

### ISSUE THREAD

**Issue by alizhd** [jordan-wright/rapportive#9]
Hey,
After the first 6 requests, it starts to give the error above. It does not let me time out or anything. 
AttributeError: 'dict' object has no attribute 'name'
I have written this small program. 

from rapportive import rapportive
def mail():
  ## open email address
    f = open('mentor_emails.txt','r')
    emails = [line.split(',') for line in f.readlines()]
    for i in range(len(emails)):
        profile = rapportive.request(emails[i][0])
        print profile.name
        print profile.jobinfo 
        print profile.memberships

**Comment by jordan-wright** [comment]
This is likely caused by the rate limiting. This is something that I'm sure it's possible to go around by using a verified email address, but I don't have the time to devote to it currently.

To check for this, you can implement a simple conditional like the one found in this function (see rapportive.py):

```
def ___process_email(email, output_file=None):
    """
    Find email address in rapportive and print profile info
    if found
    """
    profile = request(email)
    if profile and profile.success != 'nothing_useful':
        logger.info('Found match for {0}'.format(email))
        print(profile)
        if output_file:
            output_file.write(summary + '\n')
    else:
        print("No information found\n")
```

**Comment by alizhd** [comment]
Thank you so much though! You are pretty awesome. : )

**Comment by pkpp1233** [comment]
+1. I tried the fix and it only returns email addresses on successful match. Any advice on how to make sure it always returns the full output? Would be AWESOME.
